"""add guest_comment_subscriptions

Revision ID: 433bc2fc53db
Revises: b53c50d4d65b
Create Date: 2026-09-18 13:23:51.720177

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "433bc2fc53db"
down_revision: str | Sequence[str] | None = "b53c50d4d65b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_comment_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "post_id", name="uq_guest_thread_email_post"),
    )
    op.create_index(
        op.f("ix_guest_comment_subscriptions_email"), "guest_comment_subscriptions", ["email"], unique=False
    )
    op.create_index(op.f("ix_guest_comment_subscriptions_id"), "guest_comment_subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_guest_comment_subscriptions_post_id"), "guest_comment_subscriptions", ["post_id"], unique=False
    )
    op.create_index(op.f("ix_guest_comment_subscriptions_token"), "guest_comment_subscriptions", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guest_comment_subscriptions_token"), table_name="guest_comment_subscriptions")
    op.drop_index(op.f("ix_guest_comment_subscriptions_post_id"), table_name="guest_comment_subscriptions")
    op.drop_index(op.f("ix_guest_comment_subscriptions_id"), table_name="guest_comment_subscriptions")
    op.drop_index(op.f("ix_guest_comment_subscriptions_email"), table_name="guest_comment_subscriptions")
    op.drop_table("guest_comment_subscriptions")
    # ### end Alembic commands ###
