"""add_guest_thread_digest_cadence

Revision ID: 6f9557747661
Revises: 433bc2fc53db
Create Date: 2026-09-18 15:05:07.620531

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f9557747661"
down_revision: str | Sequence[str] | None = "433bc2fc53db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guest_comment_subscriptions",
        sa.Column("digest_weekly", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("guest_comment_subscriptions", sa.Column("digest_sent_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guest_comment_subscriptions", "digest_sent_at")
    op.drop_column("guest_comment_subscriptions", "digest_weekly")
    # ### end Alembic commands ###
