"""add reader_blocks

Revision ID: b53c50d4d65b
Revises: m7d9f1a3b5c7
Create Date: 2026-09-18 11:59:35.679130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b53c50d4d65b"
down_revision: str | Sequence[str] | None = "m7d9f1a3b5c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reader_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blocker_id", sa.Integer(), nullable=False),
        sa.Column("blocked_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="uq_reader_blocks_blocker_blocked"),
    )
    op.create_index(op.f("ix_reader_blocks_blocked_id"), "reader_blocks", ["blocked_id"], unique=False)
    op.create_index(op.f("ix_reader_blocks_blocker_id"), "reader_blocks", ["blocker_id"], unique=False)
    op.create_index(op.f("ix_reader_blocks_id"), "reader_blocks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reader_blocks_id"), table_name="reader_blocks")
    op.drop_index(op.f("ix_reader_blocks_blocker_id"), table_name="reader_blocks")
    op.drop_index(op.f("ix_reader_blocks_blocked_id"), table_name="reader_blocks")
    op.drop_table("reader_blocks")
    # ### end Alembic commands ###
