"""add publish_at to posts

Revision ID: bf9ccacf5b13
Revises:
Create Date: 2026-07-28 12:21:31.888165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9ccacf5b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publish_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_publish_at'), 'posts', ['publish_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_publish_at'), table_name='posts')
    op.drop_column('posts', 'publish_at')
    # ### end Alembic commands ###
