"""add_comment_notified_and_newsletter_unsubscribed

Additive round-393 columns (DEC-009 keeps every change additive):
- comments.notified_at: once-only stamp for the multi-channel approval
  fan-out, so reject→re-approve never re-fires duplicate notifications.
- newsletter_subscribers.unsubscribed_at: records a cancellation so the old
  confirm link cannot silently re-activate the address.

Revision ID: k9d2e4f6a8b1
Revises: 7f2c4a6b8d1f
Create Date: 2026-09-20 03:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "k9d2e4f6a8b1"
down_revision: str | Sequence[str] | None = "7f2c4a6b8d1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("notified_at", sa.DateTime(), nullable=True))
    op.add_column("newsletter_subscribers", sa.Column("unsubscribed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newsletter_subscribers", "unsubscribed_at")
    op.drop_column("comments", "notified_at")
    # ### end Alembic commands ###
